### ISSUE TITLE
Dependency beautifulsoup4 not needed

### ISSUE THREAD

**Issue by void-spark** [Soma-FM-Kodi-Add-On/plugin.audio.somafm#9]
Hi!

I did this a while ago: https://github.com/void-spark/xbmc-somafm
During that I found out that that the beautifulsoup4 dependency is actually unused, so could be left out of addon.xml :)

**Comment by evinr** [comment]
Nice! Feel free to submit a PR removing it from the addon.xml.

👍

**Comment by void-spark** [comment]
Boop: https://github.com/Soma-FM-Kodi-Add-On/plugin.audio.somafm/pull/11 :)

**Comment by void-spark** [comment]
I actually tested on my kodi, and runs fine :)

**Comment by evinr** [comment]
Thank you so much!!
